#!/usr/bin/env python3
# Turns PCSX2's OpenGL shader sources into a C++ table the core carries inside
# itself.
#
# Upstream reads them at runtime out of its resources directory
# (GSDevice::ReadShaderSource). A core has no resources directory: its file
# system is whatever the project mounted, and shaders are not the project's
# business - they are part of the renderer, and a core that loses them draws
# nothing. So they are compiled in, and patches/0013 answers ReadShaderSource
# from this table.
#
# Usage: gen-shaders.py <pcsx2 resources dir> <output .cpp>
import os
import sys

# The OpenGL renderer's own shaders, and the ones it shares with the other
# backends (FXAA lives there).
WANTED = ["shaders/opengl", "shaders/common"]

src_root = sys.argv[1]
out_path = sys.argv[2]

found = []
for rel in WANTED:
    d = os.path.join(src_root, rel)
    for n in sorted(os.listdir(d)):
        if n.endswith(".glsl") or n.endswith(".fx"):
            found.append((rel, n, os.path.join(d, n)))

out = [
    "/* GENERATED by waterbox/gen-shaders.py - do not edit.",
    " *",
    " * PCSX2's OpenGL shaders, compiled into the core. See the script for why.",
    " */",
    "#include <cstddef>",
    "",
    "namespace",
    "{",
    "struct ChimeraShader { const char *name; const char *text; size_t size; };",
    "",
]

table = []
for rel, n, path in found:
    with open(path, "rb") as f:
        data = f.read()
    ident = "s_" + (rel.split("/")[-1] + "_" + n).replace(".", "_").replace("-", "_")
    # A raw string literal, with a delimiter no shader contains.
    out.append('const char %s[] = R"CHIMERA(%s)CHIMERA";' % (ident, data.decode("utf-8")))
    out.append("")
    table.append((rel + "/" + n, ident))

out.append("const ChimeraShader kShaders[] = {")
for path, ident in table:
    out.append('\t{ "%s", %s, sizeof(%s) - 1 },' % (path, ident, ident))
out.append("};")
out.append("} // namespace")
out.append("")
out.append("/* Looked up by name, exactly as upstream would have opened the file. */")
out.append("const char *ChimeraFindShader(const char *name, size_t *size)")
out.append("{")
out.append("\tfor (const ChimeraShader &s : kShaders)")
out.append("\t{")
out.append("\t\tconst char *n = s.name;")
out.append("\t\tconst char *q = name;")
out.append("\t\t/* compare, treating both slashes as the same separator */")
out.append("\t\twhile (*n && *q && (*n == *q || ((*n == '/' || *n == '\\\\') && (*q == '/' || *q == '\\\\'))))")
out.append("\t\t\tn++, q++;")
out.append("\t\tif (*n == '\\0' && *q == '\\0')")
out.append("\t\t{")
out.append("\t\t\tif (size != nullptr)")
out.append("\t\t\t\t*size = s.size;")
out.append("\t\t\treturn s.text;")
out.append("\t\t}")
out.append("\t}")
out.append("\treturn nullptr;")
out.append("}")
out.append("")

with open(out_path, "w") as f:
    f.write("\n".join(out))

print("%d shaders, %d bytes" % (len(table), sum(os.path.getsize(p) for _, _, p in found)),
      file=sys.stderr)
